### ISSUE TITLE
Internal error from importing spglib

### ISSUE THREAD

**Issue by jl-wynen** [mctools/ncrystal#320]
In a new environment with unpinnend dependencies:
```bash
$ python --version
Python 3.11.10
$ python -m pip install 'ncrystal[cif]'
```
Loading an `NCMATComposer` from CIF fails with
```python
import NCrystal as NC
NC.NCMATComposer.from_cif("codid::9011998")
```
```
Querying the Crystallography Open Database for entry 9011998
Attempting to load CIF data with gemmi
/home/jl/Downloads/asd/.venv/lib/python3.11/site-packages/NCrystal/cifutils.py:1566: NCrystalUserWarning: SG-227 available in multiple choices ("F d -3 m:1", "F d -3 m:2") and which one was not encoded explicitly in the _space_group_name_H-M_alt CIF field. Consider overriding the space group explicitly when loading this file.
  _nc_common.warn(f'SG-{sg.number} available in multiple'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jl/Downloads/asd/.venv/lib/python3.11/site-packages/NCrystal/ncmat.py", line 127, in from_cif
    return NCMATComposer( Impl.from_cif( cifsrc=cifsrc, quiet=quiet,
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jl/Downloads/asd/.venv/lib/python3.11/site-packages/NCrystal/_ncmatimpl.py", line 200, in from_cif
    lc = nc_cifutils.CIFLoader( cifsrc, quiet = quiet, mp_apikey = mp_apikey,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jl/Downloads/asd/.venv/lib/python3.11/site-packages/NCrystal/cifutils.py", line 275, in __init__
    load, gemmi, struct = _actual_init_gemmicif( cifsrc,
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jl/Downloads/asd/.venv/lib/python3.11/site-packages/NCrystal/cifutils.py", line 1793, in _actual_init_gemmicif
    cellsg, final_atoms, warnings, msgs = _impl_refine_cell( cellsg, final_atoms )
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jl/Downloads/asd/.venv/lib/python3.11/site-packages/NCrystal/cifutils.py", line 1132, in _impl_refine_cell
    d = _nc_ncmatimpl._spglib_refine_cell( orig_cell )#, symprec = 0.01, allow_axis_swap = True )
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jl/Downloads/asd/.venv/lib/python3.11/site-packages/NCrystal/_ncmatimpl.py", line 1902, in _spglib_refine_cell
    refined_cell, symdata = _impl_spglib_refine_cell( spglib_cell, symprec=symprec, warnings=warnings, msgs=msgs )
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jl/Downloads/asd/.venv/lib/python3.11/site-packages/NCrystal/_ncmatimpl.py", line 1938, in _impl_spglib_refine_cell
    spglib = _import_spglib()
             ^^^^^^^^^^^^^^^^
  File "/home/jl/Downloads/asd/.venv/lib/python3.11/site-packages/NCrystal/_ncmatimpl.py", line 1845, in _import_spglib
    return spglib.spglib
           ^^^^^^^^^^^^^
AttributeError: module 'spglib' has no attribute 'spglib'. Did you mean: '_spglib'?
```

There was a recent update to spglib that seems to cause this. When I install with
```bash
$ python -m pip install 'ncrystal[cif]' 'spglib<2.7'
```
I don't get the error.

This tripped up our nightly test here: https://github.com/scipp/essdiffraction/actions/runs/20704635147/job/59432674201

**Comment by tkittel** [comment]
Release 4.2.12 is out, so NCrystal should again work with all spglib releases >=2.1.0. Thanks for the report @jl-wynen!
